spring:

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/final_board
    username: juny
    password: juny

  web:
    resources:
      static-locations:
        - classpath:/static/
        - classpath:/public/
        - classpath:/resources/
        - classpath:/META-INF/resources/

  servlet:
    multipart:
      enabled: true
      max-file-size: 2MB

decorator:
  datasource:
    enabled: false

mybatis:
  mapper-locations: classpath:repository/*.xml
  type-aliases-package: com.juny.finalboard

resources:
  image-resource: "/Users/jijunhyuk/JunyProjects/ebrainsoft/images/"
  attachment-resource: "/Users/jijunhyuk/JunyProjects/ebrainsoft/attachments/"

jwt:
  secret-key: js82k!@398sdafla8xcvjzxsdfias93k4a90asdf021jl1asdf098123kj
  access-token-expired-mile-second: 600_000_000